### ISSUE TITLE
create_client_credentials.pl: Option checked but not available in list of GetOptions call

### ISSUE THREAD

**Issue by horkko** [kjolley/BIGSdb#268]
Hi Keith,

It looks like you've missed to add the support for option `-p|permission` in GetOptions call for `create_client_credentials.pl` script.
So this call `./create_client_credentials.pl -a curl -i -p 'allow'` fails : 
```
Unknown option: p
Error in command line arguments
```
Could you please fix this missing?
Thanks

Emmanuel

**Comment by kjolley** [comment]
Hi Emmanual,

Thanks for the bug report - now fixing.
