### ISSUE TITLE
Only one scheme field should be set as primary key

### ISSUE THREAD

**Issue by kjolley** [kjolley/BIGSdb#272]
This is checked when adding scheme fields separately but not in batch mode.
This will also be necessary for classification scheme fields.

**Comment by jgugliel** [comment]
Hi Keith,
I have the feeling that this could be related to an issue a user recently told me about.
She created two scheme fields for one single scheme. One called `cg` is set as primary key. The other one called `CT` is not set as primary key.
She wants to update the `CT` values. When she does that separately, no problem. But she cannot do that in batch mode. The error message says 

> no action - new cg already exists or has been retired

Given the error message, I understand that BIGSdb is trying to update `cg`, even though the data the batch table looks like

> cg   Field   New_value
2   CT   304
3   CT   83
4   CT   188
...


So what do you think? Is it the same bug? Is there anyway to deal with it?

Thanks!

-- Julien

**Comment by kjolley** [comment]
Hi Julien,
It is a bug, but it's not the same one. I am to replicate this - will take a look.

Best wishes
Keith

**Comment by jgugliel** [comment]
After more tests on our side, it seems that the batch update runs fine right after the fields are created. Apparently the problem appears after the update_cache script is run for the first time. I don't know if this is relevant or not...

**Comment by kjolley** [comment]
It should be fixed in the commit mentioned above.

**Comment by jgugliel** [comment]
Sorry I didn't see the commit. I'll ask Emmanuel to apply the fix and will keep you posted.

Thanks a lot
-- Julien

**Comment by jgugliel** [comment]
Keith,

The fix worked.

Thanks !
