### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by kjolley** [kjolley/BIGSdb#276]
It would be useful to have fields which become compulsory depending on the values set in other fields.

**Comment by jgugliel** [comment]
Hi Keith,

This is a really interesting enhancement for BIGSdb.
In your mind, would this feature allow to perform the following: I use the cluster.pl script to perform single linkage clustering on my data. So each isolate belong to a cluster. Now I know that my cluster number 23 corresponds in the literature to a known group, "Group 48". Would it be possible to automatically fill a field with values according to predefined rules like : if cluster==23, then field becomes Group 48?

Another example: I know that ST 1, 2, 3 and 4 of my genus all belong to the same species. ST 5, 6 and 7 belong to another species. Then a field "species" could automatically be filled with species 1 or species 2 according to the results of the scans.

Would something like that be possible?

**Comment by kjolley** [comment]
Hi Julien,
This is specifically meant for isolate table (provenance) fields. It would be required for things like where you have a 'disease' field with a list of allowed values, with one of those values being 'other'. We could make it so that if 'other' was selected, then the user would have to enter something in to a 'detailed_disease' field for example.

For adding information to cluster groups I will create a new ticket. This would just be an editable field associated with each group.

Your example for STs is already possible - you just need to create a non-primary key field for the scheme called 'species'. This is editable in the web interface. This is used for assigning STs to clonal complexes in Neisseria and Campylobacter databases.

**Comment by kjolley** [comment]
It would also be useful to be able to state that one date field, or one integer field, should have a lower or higher values than another field.

**Comment by kjolley** [comment]
Now implemented using field validation rules.
