### ISSUE TITLE
Extract typing information from genomes via API

### ISSUE THREAD

**Issue by kjolley** [kjolley/BIGSdb#313]
This may require a queuing system to be implemented as it could easily overload the server if all requests ran on receipt.

**Comment by hvbakel** [comment]
I just sent an email requesting this same feature, which would be fantastic to get implemented.

**Comment by kjolley** [comment]
Documentation for API call can be found at http://bigsdb.readthedocs.io/en/latest/rest.html#db-schemes-scheme-id-sequence.
