### ISSUE TITLE
Deprecated use of `version` ?

### ISSUE THREAD

**Issue by horkko** [kjolley/BIGSdb#324]
Hi Keith,

I've installed `BIGSdb 1.15.4` without problems.
However, from the web site, clicking `About BIGSdb`, it brings me to the Info page but the `BIGSdb` version is not displayed. So I thought maybe the use of `version.pm` in `Application.pm` is depracted?
This is what I've seen on `metacpan.org`.

```perl
use version; our $VERSION = version->declare("v1.2.3"); # formal
use version; our $VERSION = qv("v1.2.3");               # deprecated
use version; our $VERSION = qv("v1.2_3");               # deprecated
```
And in `Application.pm`
```perl
use version; my $VERSION = qv('v1.15.4');
```
This is the version installed at home:
```
[bigsdb@kubiak bigsdb]$ perl -Mversion -e 'print "$version::VERSION\n";'
0.9907
```

Cheers

Emmanuel

**Comment by horkko** [comment]
Keith,
Forget about my issue, it was a path issue :( sorry

Emmanuel

**Comment by kjolley** [comment]
Hi Emmanuel,

Glad it's not a problem but as the current use seems to be deprecated I should look to update this anyway.  Thanks.
