### ISSUE TITLE
Creating scheme field with uppercase throws SQL error when removed

### ISSUE THREAD

**Issue by horkko** [kjolley/BIGSdb#343]
Hi Keith,

We've just faced a problem with some schemes a user wanted to delete using the interface.
He created it with a mix of upper and lower case as shown below:

```
# select * from schemes;
 scheme_id |   field   
-----------+-----------
         4 | VF
         1 | Y_cgST
         5 | testST
         2 | yeen_cgst
         3 | yeps_cgst
```
So, when we want to delete a scheme using the web interface, it fails throwing an SQL error:

```
DELETE FROM scheme_fields WHERE (scheme_id,field)=(?,?)
ERROR: syntax error at or near "=" LINE 1: UPDATE mv_scheme_1 SET Y_cgST=null WHERE = ^ QUERY: UPDATE mv_scheme_1 SET Y_cgST=null WHERE = CONTEXT: PL/pgSQL function modify_profile_field() line 22 at EXECUTE statement at /opt/bigsdb/lib/BIGSdb/CurateDeletePage.pm line 429.
```
As some constraint apply in cascade to scheme_fields, mv_scheme_1, profile_fields and so on...
And as you know, by default, when a column name is created with PostgreSQL, uppercase letter are automatically lowered :
```
# create table test(ID int, NaMe text);
CREATE TABLE
# \d test
     Table "public.test"
 Column |  Type   | Modifiers 
--------+---------+-----------
 id     | integer | 
 name   | text    | 
```

So I suggest that some checking should take place just before creating new scheme(s) name using the interface or using any script to either, throw an error to warn the user only lowercase are permitted, or to automatically lower scheme name and let the user know it ?
Let me know what do you think about it?

Regards

Emmanuel

**Comment by horkko** [comment]
Or another alternative would be to force quoting fields when SQL query are generated ? 
```
UPDATE mv_scheme_1 SET "Y_cgST"=null WHERE...
```

**Comment by kjolley** [comment]
The capitalization isn't the problem. 

The issue is that by deleting a scheme field, some stored procedures are triggered that assume the field still exists.  Try running the attached against the seqdef database. This fixes these methods to explicitly check that the primary key field exists.

[Fix_profile_trigger_methods.txt](https://github.com/kjolley/BIGSdb/files/636481/Fix_profile_trigger_methods.txt)

**Comment by horkko** [comment]
Thanks for this fixes.
However, I'm still convince that there is a problem with capitalization, however in table `mv_scheme_<id>`.
This is what I've mentioned in my first message, when the tables `mv_scheme_<id>` are updated, the generated SQL queries (stored procedures `modify_profile_field`) are wrong as shown below:

```
# select * from schemes;
 scheme_id |   field   
-----------+-----------
         4 | VF
         1 | Y_cgST
         5 | testST
         2 | yeen_cgst
         3 | yeps_cgst

# \d mv_scheme_1
     Table "public.mv_scheme_1"
    Column    |  Type   | Modifiers 
--------------+---------+-----------
 y_cgst       | text    | not null
 sender       | integer | not null
 curator      | integer | not null
 date_entered | date    | not null
 datestamp    | date    | not null
 profile      | text[]  | 

```
As you can see, the field `Y_cgST` from scheme 1, is lowered as column name in table `mv_scheme_1` which lead to an error when this table is updated (Triggered SQL code)
```
# UPDATE mv_scheme_1 SET Y_cgST=null WHERE ...
```

And from the stored procedure `modify_profile_field` we will still have the issue:
```
...
IF (TG_OP = 'DELETE') THEN	
			--If PK scheme field is deleted, this function is still triggered.
			IF (pk IS NOT NULL) THEN
				EXECUTE FORMAT('UPDATE %I SET %s=null WHERE %s=$1',scheme_table,OLD.scheme_field,pk) USING OLD.profile_id;
			END IF;
			RETURN OLD;
...
```
`%s` will be replaced with `Y_cgST` which is not the name of the column. It should be lowered or quoted as far as I will understand the procedure code.

Am I wrong?

**Comment by kjolley** [comment]
I think you are wrong. Postgres doesn't care about the capitalization of the field when used in a query.

**Comment by horkko** [comment]
Yes you're right I'm wrong 👍 . I've been confused with another application for which we add similar problem and it was with column names with mixed lower and upper case. But I can't remember the context. Anyway, sorry for this but we had some issue anyway :)

**Comment by kjolley** [comment]
No worries.

**Comment by horkko** [comment]
Digging the Postgres error log, that's what I've found:

```
UPDATE mv_scheme_1 SET Y_cgST=null WHERE =$1
```
It looks like the `WHERE` clause is incomplete.
Your fixes should avoid this incomplete `WHERE` in the future, thanks  👍
