### ISSUE TITLE
Add security or granted users for config repair page?

### ISSUE THREAD

**Issue by horkko** [kjolley/BIGSdb#353]
Hi Keith,

Hope you're doing well? By the way, happy new year 👍 
We've faced a potentially dramatical problem yesterday and today when a user started to use the `ConfigRepair` page to rebuild a scheme (warehouse tables).
As soon as the user clicked the `Rebuild` button, we've seen the CPU usage on our `postgres` server to stack to 100% for the rebuild process for more than an hour. We've been forced to kill the process.
It was impossible to have info about the table (`mv_scheme_<id>`) by simply typing `\d mv_scheme_<id>`.
The SQL function called is `initiate_scheme_warehouse`. So maybe there's a problem with this function? The table has less than 2000 rows.
This is problematic as yesterday it made the server to run out of memory and restart 👎 
So, my question is, do you think this could be a good or bad idea to set some `superuser` to be able to run such rebuild and be able to do it at night without impacting other application/databases?
A list of super user that could be set/configured in `bigsdb.conf` file?

Let me know what do you think about it.
Regards
Emmanuel

**Comment by kjolley** [comment]
Hi Emmanuel,

This is already an admin function - the user has to be either an admin or have specific permission to modify loci or schemes. A standard curator can't run this.

How much memory has your server got?

**Comment by horkko** [comment]
Hi,

OK I think I'll update user privileges.
Our server is 32GB and configured with 8Gb of shared buffer.

**Comment by kjolley** [comment]
I think you're probably pushing it on the memory if you're running cgMLST schemes.

**Comment by kjolley** [comment]
By the way, did you modify the postgresql temp_buffers value as advised when upgrading to version 1.14?

See https://github.com/kjolley/BIGSdb/blob/develop/Upgrading_README.txt#L314-L326.

**Comment by horkko** [comment]
Hi
No I did not do it. However we ' ve been in 1.15 for quite long time and we did not encounter this problem before. I ll try this set up. thanks

**Comment by kjolley** [comment]
Check out https://github.com/kjolley/BIGSdb/issues/354. Seems like this may be a fix.

**Comment by horkko** [comment]
Hi
I know he is my office colleague we've been working together on this this all afternoon 😉

**Comment by kjolley** [comment]
Ah ok!  Not such a coincidence then. :-)

**Comment by horkko** [comment]
Nope :)
