### ISSUE TITLE
mySQL reserved words as field names

### ISSUE THREAD

**Issue by jgugliel** [kjolley/BIGSdb#359]
Keith,

We ran into some trouble in one of our databases because we named an isolate field "references". This field was supposed to contain pubmed ids of reference articles.
The problem is that "references" is a mySQL reserved word.

Would it be possible to make reserved words usable (or non-usable) as field names ?

Bests

**Comment by kjolley** [comment]
Why would you create a references column anyway?  Reference handling is built in (with full information retrieved from PubMed) for isolates, profiles and allele data.

But yes, this is probably a good idea. Do you a full list of such reserved words? (postgreSQL not mySQL; although this shouldn't matter).

**Comment by jgugliel** [comment]
Since I generally let users create isolates, I totally forgot that reference handling was built in. So you're right, there is absolutely no need to create this column.

I found [this list](https://dev.mysql.com/doc/refman/5.7/en/keywords.html) listing SQL reserved words.

**Comment by kjolley** [comment]
Reviewing this some more, I'm not sure how this can be enforced for the isolate table, since your choice of fields, and modifying the table accordingly, is performed outside of BIGSdb.

**Comment by jgugliel** [comment]
Yes, I guess that it's something that should be handled by admins when the database is created.
