### ISSUE TITLE
Do not display email from user's profile

### ISSUE THREAD

**Issue by horkko** [kjolley/BIGSdb#372]
Hi Keith,

Do you think it would be possible not to display/expose email's user that created/curated an isolate?
As shown for example from such URL :
`http://<API_REST_URL>/db/<dbname>/users/2`

Bad user could use this REST API to get list of emails to spam them later?
What do you think? Maybe an options that could be set in `bigsdb.conf`?

Regards

Emmanuel

**Comment by kjolley** [comment]
Hi Emmanuel,

This is already the case for senders. By default, E-mails are only shown for curators/admins (this can be overridden in config.xml by setting privacy="no" to enable sender addresses to be shown, but the default is not to show them).

I think generally, the contact information for the curator should be available, but maybe it should be possible to switch this off in the REST API. I'll add a bigsdb.conf parameter.

**Comment by kjolley** [comment]
Use the following setting in bigsdb.conf: 

rest_hide_emails=1

**Comment by horkko** [comment]
Hi Keith,

Thanks for the quick fix. I'll apply it asap.
Cheers Emmanuel
