### ISSUE TITLE
internal server error  'scheme_Warehouse_indices' 

### ISSUE THREAD

**Issue by memoriasresiduais** [kjolley/BIGSdb#389]
Dear Keith,

We are experiencing some errors in BIGSdb-Listeria which we are trying to understand and eliminate.
We detected them with the configuration check:
====
_Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request._
=====

It probably relates to the fact that I eliminated the scheme fields from cgMLST1748. These are no longer in any of the databases, but Emmanuel sees the following:

====
_the 'scheme_Warehouse_indices' table is empty for scheme 3 (cgMLST1748) which causes 'BIGSdb::Scheme::_initiate' leave <pre>$self->{'locus_index'}</pre> empty and make the application failed with an internal server error._
====

Do you understand the problem and please help us fixing it?

Thanks a lot in advance!

Best regards,
Alexandra

**Comment by kjolley** [comment]
Have you tried 'Configuration repair' from the curator's (admin) page?

**Comment by horkko** [comment]
Hi Keith,
The problem is that we have an `Internal Server Error` before the page is completely loaded, so `Config Repair` link does not appear at the bottom of the page :(

Emmanuel

**Comment by kjolley** [comment]
OK, the repair page just runs the initiate_scheme_warehouse() postgres function.

You can do this manually from psql for all schemes:
SELECT initiate_scheme_warehouse(scheme_id) FROM scheme_fields WHERE PRIMARY_KEY AND 
scheme_id IN (SELECT scheme_id FROM scheme_members);

**Comment by horkko** [comment]
Hi Keith,

I've tried as you said, however it throws an SQL error as shown below.

```sql
SELECT initiate_scheme_warehouse(3) FROM scheme_fields WHERE PRIMARY_KEY AND scheme_id IN (SELECT scheme_id FROM scheme_members);
ERROR:  Scheme 3 does not have a primary key
CONTEXT:  SQL statement "SELECT create_scheme_warehouse(i_id)"
PL/pgSQL function initiate_scheme_warehouse(integer) line 13 at PERFORM
```

Actually the table `mv_scheme_3` does not exist. I don't know why. But the scheme exists in `schemes` table:
```sql
$ SELECT EXISTS(SELECT * FROM schemes WHERE id=3);
 exists 
--------
 t
```
Do you think I can create an empty table `mv_scheme_3` to let the function `initiate_scheme_warehouse` perform correctly?

Thx

Emmanuel

**Comment by kjolley** [comment]
You changed the SQL from what I typed. Don't change scheme_id to 3. Type exactly the following:
```
SELECT initiate_scheme_warehouse(scheme_id) FROM scheme_fields WHERE PRIMARY_KEY AND
scheme_id IN (SELECT scheme_id FROM scheme_members);
```

The problem is that scheme_3 does not have a primary key field. That SQL error message is informative.

Scheme cache tables, e.g. mv_scheme_3, are only created for schemes with a primary key field. Schemes without this are simply collections of loci, but then they shouldn't have non-primary key scheme fields.

**Comment by horkko** [comment]
Ok, DONE. Thanks, it went ok for `seqdef`.
However, the problem we encouter, is for an `isolates` database :( and unfortunately, `initiate_scheme_warehouse` is not found in this db.
Do you have any clue? Sorry for bothering you.

Emmanuel

**Comment by kjolley** [comment]
What messages are you seeing in bigsdb.log, apache error.log and progresql.log?

**Comment by kjolley** [comment]
You need to make sure that the scheme in the isolate database reflects the scheme in the seqdef database (scheme_fields, scheme_members).
You then need to refresh the scheme cache.
Use the update_scheme_caches.pl script.

**Comment by horkko** [comment]
From `error.log`:
```
Use of uninitialized value in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 125.
Use of uninitialized value in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 125.
Use of uninitialized value in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 125.
Use of uninitialized value in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 125.
Use of uninitialized value in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 125.
```

From `bigsdb.log`:
```
2017/03/16 14:52:48 [INFO] 157.99.101.110 Scan.pm:539  - Scan pubmlst_listeria_isolates:BIGSdb_23430_1489654328_12673 (Alexandra Moura) finished
2017/03/16 14:54:07 [WARN] 157.99.101.111 Scheme.pm:143  - Check database attributes in the scheme_fields table for scheme#3 (cgMLST1748)! DBD::Pg::st execute failed: ERROR:  syntax error at or near "]"
LINE 1: SELECT  FROM mv_scheme_3 WHERE (profile[]=$1 OR profile[]='N...
                                                ^ at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 141.
 
2017/03/16 14:54:08 [ERROR] 157.99.101.111 Scheme.pm:41  - DBD::Pg::st execute failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 40.
```

From `bigsdb_error.log`:
```
 DBD::Pg::st fetchall_arrayref failed: no statement executing at /opt/bigsdb/lib/BIGSdb/Scheme.pm line 42.\n
```
The problem comes initially from `BIGSdb::Scheme::_initiate` where the SQL query does not return any rows from `seqdef` db.

**Comment by horkko** [comment]
From your last comment, this is what we have in both databases (`isolates` and `seqdef`) for our problematic scheme 3:
```sql
[pubmlst_bigsdb_listeria_seqdef] =# select count(*) from scheme_members where scheme_id = 3;
 count 
-------
  1748
(1 row)

[pubmlst_bigsdb_listeria_seqdef] =# select count(*) from scheme_fields where scheme_id = 3; count 
-------
     0
(1 row)

[pubmlst_bigsdb_listeria_seqdef] =# \c pubmlst_bigsdb_listeria_isolates 
[pubmlst_bigsdb_listeria_isolates] =# select count(*) from scheme_members where scheme_id = 3;
 count 
-------
  1748
(1 row)

[pubmlst_bigsdb_listeria_isolates] =# select count(*) from scheme_fields where scheme_id = 3;
 count 
-------
     0
(1 row)
```
Then refreshing the scheme cache for scheme id 3 in `isolates` db does not do anything as:
```Scheme 3 (cgMLST1748) does not have a primary key - skipping.``` :(

**Comment by kjolley** [comment]
OK, that's expected if there are no scheme fields - there is nothing to cache.

And what about the schemes table for scheme 3 (isolate database)?
If this scheme is now just a collection of loci, there should be no value set for dbase_name and dbase_id.

**Comment by horkko** [comment]
@memoriasresiduais Could you confirm?
@kjolley Nop, both values are set
```sql
[pubmlst_bigsdb_listeria_isolates] =# select id,dbase_name,dbase_id from schemes where id=3;
 id |           dbase_name           | dbase_id 
----+--------------------------------+----------
  3 | pubmlst_bigsdb_listeria_seqdef |        3
```

Should I unset these values from `isolates` database?

**Comment by horkko** [comment]
From @memoriasresiduais : "Yes, cgMLST is just a collection of 1748 loci"

**Comment by kjolley** [comment]
Yes, set both dbase_name and dbase_id to null for scheme 3.

**Comment by kjolley** [comment]
Any luck fixing this? I have just received a report that the Listeria MLST profiles are no longer available on PubMLST - we web-scrape these from your database (http://bigsdb.pasteur.fr/perl/bigsdb/bigsdb.pl?db=pubmlst_listeria_seqdef_public), so I'm guessing this is the same issue.

**Comment by memoriasresiduais** [comment]
Hi Keith,

Thanks for your emails.
We are aware of the problem. In fact, MLST and serogroup scheme_fields disappeared from isolatedb, whereas in seqdb we have the scheme_fields but not the allelic profiles. Rebuilding the schemes did not so fix the problem.
Emmanuel is on it, I think.
Any help would be much appreciated, as always!

Thanks,
Alexandra



De : Keith Jolley [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 14:02
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


Any luck fixing this? I have just received a report that the Listeria MLST profiles are no longer available on PubMLST - we web-scrape these from your database (http://bigsdb.pasteur.fr/perl/bigsdb/bigsdb.pl?db=pubmlst_listeria_seqdef_public), so I'm guessing this is the same issue.

**Comment by horkko** [comment]
Hi Keith

Setting both `dbase_name` and `dbase_id` to null fixed the issue for scheme 3 but it looks now other schemes have similar problem. Do you think calling SQL procedures could have lead to our current problem?  I am not ease with the biological aspect so if you could help us withwe would really appreciate this. 
I am currently off for holidays.

**Comment by kjolley** [comment]
No, I don't think this would cause any issues. These procedures are just for cache generation and maintenance. Can you confirm that all the required primary data are in the seqdef database profile_members and profile_fields tables? Be aware that any changes to a scheme utilizing a primary key field in the seqdef database will result in the removal of profile data (a fairly prominent warning is shown in the web interface if you attempt to do this).

**Comment by memoriasresiduais** [comment]
I confirm that all data regarding scheme_members and scheme_fields are correct in both seqdb and isolatedb….

De : Keith Jolley [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 16:37
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


No, I don't think this would cause any issues. These procedures are just for cache generation and maintenance. Can you confirm that all the required primary data are in the seqdef database profile_members and profile_fields tables? Be aware that any changes to a scheme utilizing a primary key field in the seqdef database will result in the removal of profile data (a fairly prominent warning is shown in the web interface if you attempt to do this).

**Comment by kjolley** [comment]
But are the profile data there? profile_members and profile_fields.

**Comment by horkko** [comment]
@kjolley Should be the scheme_members and the profile_members be the same number?

**Comment by memoriasresiduais** [comment]
I don’t understand what you mean, sorry.
All seems to be ok with the scheme_fields and scheme_members (they were not changed).
At seqdb the profiles appear as the following:

[cid:image001.png@01D2A19A.245F8140]


And at isolatesdb:

[cid:image002.png@01D2A19A.245F8140]


Running the update_scheme_caches.pl script returns the following error:

Use of uninitialized value in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/Datastore.pm line 991.

Maybe some variable was commented….?


De : Keith Jolley [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 16:43
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


But are the profile data there? profile_members and profile_fields.

**Comment by kjolley** [comment]
The scheme_fields and scheme_members tables define the scheme structure. The profiles, profile_members and profile_fields store the actual data. If you have changed the scheme_fields then you may have affected the stored data in these tables.

**Comment by horkko** [comment]
@kjolley By `changed the scheme_fields` you mean using the web interface? Because I did not change anything by hand in the database.

**Comment by memoriasresiduais** [comment]
Through the interface I cannot see any tab regarding profile_members or profile_fields..
The MLST and serogrp schemes were not touched on my side either.


De : Emmanuel Quevillon [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 17:55
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


@kjolley<https://github.com/kjolley> By changed the scheme_fields you mean using the web interface? Because I did not change anything by hand in the database.

**Comment by kjolley** [comment]
Yes. If you modify scheme_fields or scheme_members (in the seqdef database) via the web interface you will remove profile data, because this is modifying the structure of the scheme.

The profile_members and profile_fields are tables within the database - you don't modify them directly via the web interface. They are populated when you upload profile data.

**Comment by memoriasresiduais** [comment]
Nothing was touched or modified on scheme_fields or scheme_members (in the seqdef database) via the web interface.

De : Keith Jolley [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 18:01
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


Yes. If you modify scheme_fields or scheme_members (in the seqdef database) via the web interface you will remove profile data, because this is modifying the structure of the scheme.

The profile_members and profile_fields are tables within the database - you don't modify them directly via the web interface. They are populated when you upload profile data.

**Comment by kjolley** [comment]
I was basing this on the very first message: "It probably relates to the fact that I eliminated the scheme fields from cgMLST1748."

**Comment by kjolley** [comment]
Anyway, can you confirm that the profile_members and profile_fields tables (seqdef database) are populated with what you expect the values to be?

**Comment by horkko** [comment]
@memoriasresiduais @kjolley So we are facing a strange problem then?
@kjolley It looks now that this problem is solved as I set to `NULL` `dbase_name` and `dbase_id` in the database manually.
But, anyhow, I don't know if this is related, but schemes 2 and 4 (`MLST and serogroup`) are now empty of allelic profiles (in seqdb). From @memoriasresiduais  "MLST and serogroup scheme_fields disappeared from isolatedb, whereas in seqdb we have the scheme_fields but not the allelic profiles."

**Comment by memoriasresiduais** [comment]
Yes, the cgMLST scheme fields were deleted some months ago.
The MLST and sero scheme problem appear last Friday (at least it working well on Wednesday, Thursday I don’t know). MLST and serogrp schemes were not touched.

De : Keith Jolley [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 18:12
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


I was basing this on the very first message: "It probably relates to the fact that I eliminated the scheme fields from cgMLST1748."

**Comment by memoriasresiduais** [comment]
Just to be clear,
MLST and serogroup scheme_fields information disappeared from isolatedb, whereas in seqdb we have the scheme_fields but no information on the allelic profiles.

I.e. the fields appear in both database, but the info on them is empty (one with only profiles, the other only with the info on the scheme_fields).


De : Emmanuel Quevillon [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 18:16
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


@memoriasresiduais<https://github.com/memoriasresiduais> @kjolley<https://github.com/kjolley> So we are facing a strange problem then?
@kjolley<https://github.com/kjolley> It looks now that this problem is solved as I set to NULL dbase_name and dbase_id in the database manually.
But, anyhow, I don't know if this is related, but schemes 2 and 4 (MLST and serogroup) are now empty of allelic profiles (in seqdb). From @memoriasresiduais<https://github.com/memoriasresiduais> "MLST and serogroup scheme_fields disappeared from isolatedb, whereas in seqdb we have the scheme_fields but not the allelic profiles."

**Comment by kjolley** [comment]
So we need to know if the profile data for schemes 2 and 4 are still in the database. Are there appropriate entries in the profile_members table for schemes 2 and 4 (there should be a value for each locus of each profile)? If there are, then it looks like a problem with the cache (mv_ table).

**Comment by kjolley** [comment]
If the profiles disappear from the seqdef database it is expected that the profiles remain in the isolate database but the ST field values disappear as these are populated from the seqdef database.

**Comment by memoriasresiduais** [comment]
That’s what I see through the interface, the allelic profiles for all isolates are there, but the correspondent scheme_fields (ST, CC and lineage are gone).


De : Keith Jolley [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 18:22
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


If the profiles disappear from the seqdef database it is expected that the profiles remain in the isolate database but the ST field values disappear as these are populated from the seqdef database.

**Comment by kjolley** [comment]
As I said, that is expected. The ST fields values are looked up from the seqdef database. The problem is only in the seqdef database.

**Comment by horkko** [comment]
@kjolley Do you need me to execute some SQL query(ies) to get some more info from the seqdef db?

**Comment by kjolley** [comment]
Yes.
`SELECT profile_id,locus,allele_id FROM profile_members WHERE scheme_id=2 ORDER BY profile_id;` 

You should see a value for every locus, i.e. for MLST there should be 7 rows for each profile.

**Comment by horkko** [comment]
Yes,
The query returned 3 columns without any empty value. And for each `profile_id` we have 7 rows.

**Comment by memoriasresiduais** [comment]
Ufff… happy happy joy joy!

De : Emmanuel Quevillon [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 18:45
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


Yes,
The query returned 3 columns without any empty value. And for each profile_id we have 7 rows.

**Comment by kjolley** [comment]
OK. And what about the cache table - are the profiles complete?
`SELECT * FROM mv_scheme_2;`

**Comment by horkko** [comment]
Don't know if it's normal, but 

1. We have less rows from `mv_scheme_2` (1233 rows) compare to `profile_members` (8631 rows)
2. We have 90 rows from `mv_scheme_2` where `cc` and `lineage` value are `NULL`

**Comment by memoriasresiduais** [comment]
2.      We have 90 rows from mv_scheme_2 where cc and lineage value are NULL
This is ok, I guess, since not all STs were assigned to CCs and lineage.

The other I don’t know.

De : Emmanuel Quevillon [mailto:notifications@github.com]
Envoyé : lundi 20 mars 2017 18:52
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


Don't know if it's normal, but

  1.  We have less rows from mv_scheme_2 (1233 rows) compare to profile_members (8631 rows)
  2.  We have 90 rows from mv_scheme_2 where cc and lineage value are NULL

**Comment by kjolley** [comment]
There should be 1 row per profile, so that's right. But does the profile field contain an array of 7 values? for each entry.

**Comment by horkko** [comment]
From `mv_scheme_2` all the `profile` columns are empty, no array at all :(

**Comment by kjolley** [comment]
OK. That explains the missing data.
Let's drop the cache table and recreate it.
`DROP TABLE mv_scheme_2;
SELECT initiate_scheme_warehouse(2);`

**Comment by horkko** [comment]
OK DONE.
However, the table `mv_scheme_2` looks still the same, I mean, `profile` column is still empty 😞

**Comment by memoriasresiduais** [comment]
success??

**Comment by kjolley** [comment]
Hmm. Could you check the following then:
`select * FROM scheme_warehouse_indices where scheme_id =2;`

**Comment by horkko** [comment]
Yep, 7 rows returned:
```sql
 scheme_id | locus | index 
-----------+-------+-------
         2 | abcZ  |     1
         2 | bglA  |     2
         2 | cat   |     3
         2 | dapE  |     4
         2 | dat   |     5
         2 | ldh   |     6
         2 | lhkA  |     7
```

**Comment by kjolley** [comment]
Would it be possible for you to make a pg_dump of the database and put it somewhere acccessible on the website so that I can take a look (E-mail me the link)?

**Comment by horkko** [comment]
DONE

**Comment by memoriasresiduais** [comment]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at bigsdb@pasteur.fr to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

[☹]
in seqdb and isolatedb

________________________________
De: Emmanuel Quevillon <notifications@github.com>
Enviado: 20 de março de 2017 21:12
Para: kjolley/BIGSdb
Cc: Alexandra Moura; Mention
Assunto: Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


DONE

**Comment by kjolley** [comment]
The problem is with the initiate_scheme_warehouse() function. If I replace this with the original version it works. It also works if I use the new version at https://github.com/kjolley/BIGSdb/blob/dbchanges/sql/upgrade/seqdefdb_v1.17.sql.

**Comment by memoriasresiduais** [comment]
but, but... the website is not working anymore...

<http://bigsdb.pasteur.fr/listeria/listeria.html>http://bigsdb.pasteur.fr/perl/bigsdb/bigsdb.pl?db=pubmlst_listeria_isolates_public

**Comment by kjolley** [comment]
Yes, but that is nothing to do with this problem. Your Klebsiella database is down too.

**Comment by horkko** [comment]
Ok it's back online

**Comment by memoriasresiduais** [comment]
sweet!

the problem with the MLST/serogrp schemes remain, but if you found the profiles with the scheme_fields from the db, I will be happy to have a copy, please...

**Comment by kjolley** [comment]
Replace initiate_scheme_warehouse() using the version at https://github.com/kjolley/BIGSdb/blob/dbchanges/sql/upgrade/seqdefdb_v1.17.sql. Then run:

`select initiate_scheme_warehouse(2);`

**Comment by horkko** [comment]
@kjolley We are running BIGSdb `v1.15.4`.  Is it ok to use function from `v1.17.x` ?

**Comment by kjolley** [comment]
Yes. This was the replacement function that we worked on together - it should exactly replicate the original version (introduced in v1.14) in functionality. For some reason, the function you had defined in your database dump was not quite the same as either this or the original version.

**Comment by horkko** [comment]
OK. Maybe we've made some small modifications during the optimization.
I replace with the new one.

**Comment by horkko** [comment]
OK, `profile` is back and well populated!
Thanks @kjolley !!
I will update the function for all seqdef databases.

**Comment by horkko** [comment]
@memoriasresiduais Can you check everything is OK for seqdef?

**Comment by memoriasresiduais** [comment]
Looks the same (no MLST/sero profiles)… ☹

**Comment by kjolley** [comment]
Could this be a table permission issue? I notice you have different database roles set up.

**Comment by horkko** [comment]
I don;t think so as all the tables have the same owner.
However, I've tried to refresh caches and we still have the same error :
```
** Refreshing isolates view for pubmlst_listeria_isolates
** ============================
Updating scheme 2 cache (MLST) - method: full
Use of uninitialized value in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/Datastore.pm line 991.
...
```

**Comment by horkko** [comment]
@memoriasresiduais We still have the `Internal Server Error` when we run `configuration check` but now for scheme 5 (Virulence). Like scheme 3, is scheme 5 just a collection of xx loci?
If so, I could redo the same procedure made for scheme 3, as its `dbase_name` and `dbase_id` are set (isolates db):
```sql
pubmlst_bigsdb_listeria_isolates=# select id,dbase_name,dbase_id from schemes where id=5;
 id |           dbase_name           | dbase_id 
----+--------------------------------+----------
  5 | pubmlst_bigsdb_listeria_seqdef |        5
```

**Comment by memoriasresiduais** [comment]
Yes, scheme_3 and scheme_5 are both just collections of loci (w/no associated scheme_fields).


.

**Comment by horkko** [comment]
Then I'll set to null `dbase_name` and `dbase_id`.

**Comment by horkko** [comment]
@memoriasresiduais Can you tell me which scheme(s) are only collections of loci?
As we also facing the same problem with scheme 6 now :(

**Comment by memoriasresiduais** [comment]
All schemes are collection of loci, EXCEPT scheme_2 (MLST) and scheme_4 (PCR-serogroup).

De : Emmanuel Quevillon [mailto:notifications@github.com]
Envoyé : mardi 21 mars 2017 10:28
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


@memoriasresiduais<https://github.com/memoriasresiduais> Can you tell me which scheme(s) are only collections of loci?
As we also facing the same problem with scheme 6 now :(

**Comment by memoriasresiduais** [comment]
The MLST and serogrp profiles are back!!! ☺
You guys rock!

**Comment by horkko** [comment]
Strange nothing changed since this morning 😞 
Anyway, I'll update the database to set to `NULL` values for all schemes except 2 and 4.

**Comment by horkko** [comment]
We still having some trouble running 'Configuration check` anyway:
```
Use of uninitialized value $pk in concatenation (.) or string at /opt/bigsdb/lib/BIGSdb/IsolateInfoPage.pm line 495.                             │············
Statement has no result columns to bind at /usr/local/lib64/perl5/DBI.pm line 1706.                                                              │············
 at /opt/bigsdb/lib/BIGSdb/IsolateInfoPage.pm line 495.
```

**Comment by horkko** [comment]
😭 another problem now with classification schemes

**Comment by memoriasresiduais** [comment]
either way, everything seems to be working well now, so you guys should have the break you deserve! :)

**Comment by horkko** [comment]
@kjolley Should I also delete rows related to scheme id 3 from `classification_schemes` tables?

**Comment by kjolley** [comment]
Uh yes. You can't have a classification scheme using an underlying scheme without a primary key.

**Comment by horkko** [comment]
OK. Thanks. Should I delete these rows from `classification_schemes` for both databases ? (isolates and seqdef?

**Comment by kjolley** [comment]
Yes. They need to be set the same.

**Comment by horkko** [comment]
I think we're done at last!
Configure check is working without errors anymore
Thanks a lot Keith for your time and your advices.

**Comment by kjolley** [comment]
No worries. Enjoy your holiday!

**Comment by memoriasresiduais** [comment]
Bravo, thanks a lot to you both!
Happy holidays!

De : Emmanuel Quevillon [mailto:notifications@github.com]
Envoyé : mardi 21 mars 2017 12:20
À : kjolley/BIGSdb <BIGSdb@noreply.github.com>
Cc : Alexandra Moura <amoura@ua.pt>; Mention <mention@noreply.github.com>
Objet : Re: [kjolley/BIGSdb] internal server error 'scheme_Warehouse_indices' (#389)


I think we're done at last!
Configure check is working without errors anymore
Thanks a lot Keith for your time and your advices.
