### ISSUE TITLE
Add classification groups to profile downloads page.

### ISSUE THREAD

**Issue by kjolley** [kjolley/BIGSdb#399]

**Comment by jgugliel** [comment]
Hi Keith. I see you just posted this thanks! Having the groups appear on the profile downloads will be greatly appreciated here.
You changed the title because you won't add the groups to the profile information page?

**Comment by kjolley** [comment]
That's my initial thought because the clustering is probably only used for cgMLST and the profile info page for these profiles isn't particularly useful.
