### ISSUE TITLE
Using request->path instead of request->uri

### ISSUE THREAD

**Issue by yghorbal** [kjolley/BIGSdb#492]
I'm trying to make the REST API service run using Plack::Handler::Apache2 and a prefix on the main domain of the app (os that I don't need to have a dedicated domain and have specific processes for the API service) In fact BIGSdb cgi scripts are already running inside Apache.

The Apache config looks like 
```
<Location /api>
    SetHandler perl-script
    PerlResponseHandler Plack::Handler::Apache2
    PerlSetVar psgi_app /path/to/bigsrest.pl
    Require all granted
</Location>
```
This config breaks because of the check done here 

https://github.com/kjolley/BIGSdb/blob/ec0fbc81f42318f22eecfb415d067b6685285f39/lib/BIGSdb/REST/Interface.pm#L113-L114

This check fails since the request->uri call will return the full URI (prefixed with /api in my case) and the regex will not validate. I suggest using request->path that strips the base and the check will work as intended.

I tested swapping the two calls and everything was working OK (even uri_for returns correct URLs  in the JSON body)

Is it possible to replace  request-uri by request->path ?

**Comment by kjolley** [comment]
Hi - yes, no problem. I've made this change. Thanks for the insight about running it under Plack::Handler::Apache2.
