### ISSUE TITLE
Some questions about the error

### ISSUE THREAD

**Issue by HEQILU951221** [kjolley/BIGSdb#534]
I am sorry that I don't have any Linux foundations, I have learned some to use BIGSdb. But it still not finished building. And following is some errors and failures in bigsdb.log. 
Finally I want to use its cgMLST in my research.
Please help me, thank you very much.

2018/11/12 05:45:23 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet fontawesome-all.css not found!
2018/11/12 05:45:23 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet bigsdb.css not found!
2018/11/12 05:46:12 [ERROR] 127.0.0.1 Dataconnector.pm:103  - Cannot connect to database 'bigsdb_auth' (localhost). DBI connect('host=localhost;port=5432;dbname=bigsdb_auth','apache',...) failed: FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "apache", database "bigsdb_auth", SSL on
FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "apache", database "bigsdb_auth", SSL off at /usr/local/lib/BIGSdb/Dataconnector.pm line 98.
2018/11/12 05:46:12 [ERROR] 127.0.0.1 BaseApplication.pm:303  - Cannot connect to authentication database 'bigsdb_auth'
2018/11/12 05:46:12 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet fontawesome-all.css not found!
2018/11/12 05:46:12 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet bigsdb.css not found!
2018/11/12 05:56:28 [FATAL] [undef] BaseApplication.pm:329  - bigsdb.conf file is not accessible.
2018/11/12 06:27:06 [FATAL] [undef] BaseApplication.pm:329  - bigsdb.conf file is not accessible.
2018/11/12 06:31:12 [FATAL] [undef] BaseApplication.pm:329  - bigsdb.conf file is not accessible.
2018/11/12 06:47:59 [FATAL] [undef] BaseApplication.pm:329  - bigsdb.conf file is not accessible.
2018/11/12 06:47:59 [ERROR] 127.0.0.1 BaseApplication.pm:176  - Invalid curate script path - /cgi-bin/bigscurate.pl
2018/11/12 06:47:59 [ERROR] 127.0.0.1 BaseApplication.pm:303  - Cannot connect to authentication database ''
2018/11/12 06:48:00 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet fontawesome-all.css not found!
2018/11/12 06:48:00 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet bigsdb.css not found!
2018/11/12 06:54:58 [FATAL] [undef] BaseApplication.pm:329  - bigsdb.conf file is not accessible.
2018/11/12 06:54:58 [ERROR] 127.0.0.1 BaseApplication.pm:176  - Invalid curate script path - /cgi-bin/bigscurate.pl
2018/11/12 06:54:58 [ERROR] 127.0.0.1 BaseApplication.pm:303  - Cannot connect to authentication database ''
2018/11/12 06:54:58 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet fontawesome-all.css not found!
2018/11/12 06:54:58 [ERROR] 127.0.0.1 Page.pm:484  - Stylesheet bigsdb.css not found!

**Comment by HEQILU951221** [comment]
And I am setting up the version of 1.19.1.

**Comment by kjolley** [comment]
Can you confirm that you have read and followed the step-by-step installation instructions at https://bigsdb.readthedocs.io/en/latest/installation.html? Step 8 here, would copy the bigsdb.conf file to the /etc/bigsdb directory on your server.

Have you created the required databases - step 10?

**Comment by kjolley** [comment]
What cgMLST do you want to use? BIGSdb is the software platform that runs PubMLST. You don't need to install it to use one of these schemes, only if you are going to set up your own to run locally.

**Comment by HEQILU951221** [comment]
Yes, I did the step 8 and 10.
And I want to use the cgMLST plan of listeria and know CTs.

**Comment by kjolley** [comment]
Can you confirm then that the bigsdb.conf file exists in /etc/bigsdb? If you type 
`cat /etc/bigsdb/bigsdb.conf` you should see the contents of the configuration file.

You don't need to install BIGSdb in order to use the Listeria cgMLST scheme. This is hosted on the Pasteur BIGSdb website (http://bigsdb.pasteur.fr/listeria/listeria.html), and installing BIGSdb won't help you immediately use this scheme because you will then need to upload all the scheme data (the software comes with empty databases that you need to populate). BIGSdb is intended for hosting of schemes and has been written to run the PubMLST website, but unless you plan to run such a website yourself most end users do not need to run it locally.

**Comment by HEQILU951221** [comment]
Yes I can see the contents of this file.

On the Pasteur BIGSdb website, put my data in the "Batch sequence query - Listeria locus/sequence definitions". The Allele number will be put out, but how can I use that to know CTs. I'm sorry for asking such a strange question.
And thank you very much for your reply. This is very timely for me.

**Comment by kjolley** [comment]
Batch sequence query is for querying multiple (short) records at the same time (https://bigsdb.readthedocs.io/en/latest/data_query.html#querying-multiple-sequences-to-identify-allele-identities), usually against a single locus. You are querying a single (genome) sequence, so you need to use the standard sequence query form (https://bigsdb.readthedocs.io/en/latest/data_query.html#querying-sequences-to-determine-allele-identity).

To retrieve CTs, you will need to select the appropriate scheme in the dropdown box and paste in (or upload) your genome. However, classification scheme clustering for a query genome (which is how CTs are implemented) was introduced with BIGSdb 1.20.0. The Pasteur site is currently running v1.17.0, but they announced today (to their registered users) that they will be updating on Tuesday 20 November. You should contact them about specific instances of BIGSdb.

**Comment by HEQILU951221** [comment]
Thank you very much for your reply, 
the problem of retrieving CTs has been bothering me for a long time.
I will try to contact Pasteur site for more information.
