### ISSUE TITLE
How to enable iTOL plugin

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#567]
Dear Keith

I did not manage to have the iTOL button available for the users (compare to GrapeTree we/they see it is missing). We have `Archive::Zip` following dependencies of https://bigsdb.readthedocs.io/en/latest/dependencies.html#required-packages. 

What should I also do to let user use it ?

Best regards

Bryan

## iTOL
![capture d ecran de 2019-02-18 12-08-52](https://user-images.githubusercontent.com/11556772/52947158-39c6d400-3376-11e9-851f-2029d0e991d2.png)

## GrapeTree

![capture d ecran de 2019-02-18 12-09-33](https://user-images.githubusercontent.com/11556772/52947160-3b909780-3376-11e9-9705-25213b5cc1f2.png)

**Comment by kjolley** [comment]
It doesn't seem to be generating the tree file. Do you have clustalw installed and is its path correct in bigsdb.conf?

**Comment by bryan-brancotte** [comment]
Yes it is (actually it is wrapped and sent to a cluster), and the path is correct in bigsdb.conf

**Comment by bryan-brancotte** [comment]
We check the alignment in the fasta and it is done. What is the software used to create the tree ?

**Comment by kjolley** [comment]
clustalw - the alignment is done in mafft.

**Comment by kjolley** [comment]
Did you fix this?

 - it is working for me on your site.

![job status viewer klebsiella pasteurmlst](https://user-images.githubusercontent.com/7817395/53075556-62211080-34e5-11e9-81c2-5b21fafccfe1.png)

**Comment by bryan-brancotte** [comment]
Thanks for your interest in our issue. 
It surprise me a lot that it is working in production environment as I did not change anything yet. Even more surprising, it is not working in the dev environment (which should be the same !).

Where could we add some log to understand which dependency is missing ? Maybe we already can see it in the log and I missed it ?

**Comment by kjolley** [comment]
Try this: https://github.com/kjolley/BIGSdb/commit/67d25d29782194fecc9799bb71a01b453c665e16

**Comment by bryan-brancotte** [comment]
Using https://github.com/kjolley/BIGSdb/pull/569
```log
2019/02/20 10:47:55 [ERROR] ITOL.pm:368  - Tree file has not been generated.
2019/02/20 10:47:55 [DEBUG] ITOL.pm:374  - CLUSTALW program has been found at /opt/bigsdb/wrappers/clustalw/clustalw2 and is executable.
```

I am investigating if this could be a side effect of the deported computation

**Comment by bryan-brancotte** [comment]
We found the issue, it was indeed because the deported computation. It is now solved. Thanks for your help
