### ISSUE TITLE
Using & in contry names in config.xml

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#572]
Dear Keith

We are trying to have the same configuration as you for leptospira and we have a glitch on our side with `Antigua & Barbuda` and its `&`. As we want to keep the exact same name for microreact compatibility, we need to have the same country name. How do you write it in the xml to obtain the correct display in the web interface ?

Best regards.

**Comment by kjolley** [comment]
Hi Bryan,
You need to write this as:
   <option><![CDATA[Antigua & Barbuda]]></option>

Best wishes

**Comment by jgugliel** [comment]
HA ! This was the last solution I saw, but after so many tries I was like "Yeah, let's message Keith, this will be easier"

**Comment by bryan-brancotte** [comment]
thanks !!!
