### ISSUE TITLE
Duplicate values in "alias" field

### ISSUE THREAD

**Issue by jgugliel** [kjolley/BIGSdb#573]
Keith,

A user wanted to batch add isolates using the template. She got the "no obvious problems identified so far" screen, but when clicking the import button, an error occurred.
Actually, all isolates had multiple aliases, and for some of them the same alias was entered twice.

Would it be possible to check for duplicate aliases before allowing the user to hit the import button?

Thanks!

**Comment by kjolley** [comment]
Yes. This can be done. It already checks that the alias is different from the isolate field - I guess I just didn't anticipate people would enter the name twice! :-)

**Comment by jgugliel** [comment]
Yes I know, I had a hard time figuring this one out - didn't think either a name would be entered twice...
