### ISSUE TITLE
Link to isolate from profileInfo when seqdef is public and has no public isolate in associated db

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#591]
Dear Keith
_Bug found thanks to Julien Guglielmini_

Our seqdef db are now public, when displaying a profile info at the bottom a link to the Isolate "Client database" is proposed, but fails for yersinia as we do not have any public isolates. 
We do not get anything in the log except apache saying that the file cannot be found

Step by step:
1. Go to https://bigsdb.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_yersinia_seqdef&page=profileInfo&scheme_id=1&profile_id=3502
2. clic on `1 isolate` at the bottom of the page

**Comment by kjolley** [comment]
I don't think this is a bug, just an error in your configuration of the client database. https://bigsdb.readthedocs.io/en/latest/administration.html#setting-up-client-databases

**Comment by bryan-brancotte** [comment]
Thanks for the quick feedback !
