### ISSUE TITLE
Sequence bin display?

### ISSUE THREAD

**Issue by alejocrojo09** [kjolley/BIGSdb#600]
Hi, I'm having problems when uploading sequence bin for an isolate. I'm following the documentation at the curator's guide: "Uploading sequence contigs linked to an isolate record". When I upload a sequence in fasta format, from the curator's interface the sequence is submitted. However, when I access to the database, it does not display the "Sequence bin" for the isolate and additionally, it does not appear the sequence bin plugin even if I have it enabled at the config.xml of the isolate database. From the curator's interface I am able to upload or delete the sequence bin but no display. How I enable this? Am I skipping a crucial part from the documentation?
Thank you for your help.

**Comment by kjolley** [comment]
Isolate info pages are cached within your browser for 1 hour - did you try refreshing the page?

How did you enable the Sequence bin breakdown plugin? Either of the following lines in config.xml should do it:

all_plugins="yes"

or

SeqbinBreakdown="yes"

**Comment by alejocrojo09** [comment]
Yes, I tried refreshing the page. In my config file I have all_plugins="yes". I tested with multiple contigs and records and still nothing.

**Comment by kjolley** [comment]
I have never encountered an issue with this.
Do you get a final confirmation (green tick) when you upload the contigs.
Are there any pertinent messages in /var/log/bigsdb.log, or the apache2 or postgresql error logs?

**Comment by alejocrojo09** [comment]
Yes, I get a confirmation for the submission. However when I check into the db in bigsdb.pl interface. It does not appear anything and shows 0 contigs. Checking at bigsdb.log, it appears an error related with SequenceExport, that MUSCLE or MAFFT is required but I don't know if it related for the sequence bin display.

**Comment by kjolley** [comment]
Also, is this a new installation or upgraded from an earlier version of BIGSdb?
Can you query the database from psql and confirm that you have both values in the sequence_bin table and in seqbin_stats? e.g. for isolate id-1;

SELECT SUM(LENGTH(sequence)) FROM sequence_bin WHERE isolate_id=1;

and

SELECT * FROM seqbin_stats WHERE isolate_id=1;

**Comment by alejocrojo09** [comment]
I have version 1.21. I just run the query in postgres from sequence_bin table I get the records for the isolate. However, in seqbin_stats there is no record at all.

**Comment by kjolley** [comment]
It seems then that there is an issue with updating the seqbin_stats table. This should be updated automatically by PostgreSQL by a trigger whenever there are changes to the sequence_bin table.

You can update the seqbin_stats table with the following:

INSERT INTO seqbin_stats (isolate_id,contigs,total_length) 
SELECT isolate_id,COUNT(id),SUM(length(sequence)) 
FROM sequence_bin GROUP BY isolate_id ORDER BY isolate_id;

In order for this to update automatically, you should check that the PostgreSQL function and trigger exist. From psql:

\df maint_seqbin_stats

should return a row. 


However, the function and trigger are defined in https://github.com/kjolley/BIGSdb/blob/develop/sql/isolatedb.sql#L428-L477. If you enter this using psql, it should fix it (CREATE TRIGGER may fail if it already exists).

**Comment by alejocrojo09** [comment]
I updated manually and it works! However, when I create a new isolatedb, in the process I get several messages:

ALTER TABLE
psql:isolatedb_v.sql:333: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "seqbin_stats_pkey" for table "seqbin_stats"
CREATE TABLE
GRANT
psql:isolatedb_v.sql:346: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "remote_contigs_pkey" for table "remote_contigs"
CREATE TABLE
GRANT
psql:isolatedb_v.sql:350: ERROR:  syntax error at or near "LANGUAGE"
LINE 1: CREATE OR REPLACE LANGUAGE 'plpgsql';
                          ^
psql:isolatedb_v.sql:362: ERROR:  language "plpgsql" does not exist
HINT:  Use CREATE LANGUAGE to load the language into the database.
psql:isolatedb_v.sql:367: ERROR:  function check_sequence_bin() does not exist
psql:isolatedb_v.sql:381: ERROR:  language "plpgsql" does not exist
HINT:  Use CREATE LANGUAGE to load the language into the database.
psql:isolatedb_v.sql:422: ERROR:  language "plpgsql" does not exist
HINT:  Use CREATE LANGUAGE to load the language into the database.
psql:isolatedb_v.sql:426: ERROR:  function check_remote_contigs() does not exist
psql:isolatedb_v.sql:473: ERROR:  language "plpgsql" does not exist
HINT:  Use CREATE LANGUAGE to load the language into the database.
psql:isolatedb_v.sql:477: ERROR:  function maint_seqbin_stats() does not exist
psql:isolatedb_v.sql:494: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "oauth_credentials_pkey" for table "oauth_credentials"

Do I need to install a special extension in order to create the trigger?
Thank you for your attention

**Comment by kjolley** [comment]
Hmm. That explains why it wasn't working originally then. 

You will need PL/pgSQL - this is usually included by default - I have never had to install it separately from PostgreSQL.

**Comment by alejocrojo09** [comment]
Thank you very much! I installed PL/pgSQL using this command for the db:

`createlang plpgsql isolate2_alecor_test`

And know it updates automatically. However, creating a new isolatedb, I still get several syntax errors:

psql:isolatedb.sql:346: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "remote_contigs_pkey" for table "remote_contigs"
CREATE TABLE
GRANT
psql:isolatedb.sql:350: ERROR:  syntax error at or near "LANGUAGE"
LINE 1: CREATE OR REPLACE LANGUAGE 'plpgsql';
CREATE FUNCTION
CREATE TRIGGER
psql:isolatedb.sql:381: ERROR:  syntax error at or near "$1"
LINE 1: INSERT INTO sequence_bin( $1 ,remote_contig,sequence, $2 , $...
                                  ^
QUERY:  INSERT INTO sequence_bin( $1 ,remote_contig,sequence, $2 , $3 ,date_entered,datestamp) VALUES ( $1 ,true,'', $2 , $3 ,'now','now') RETURNING id

Is something that is relevant for the proper performance of BIGSdb? (I'm sorry, I'm not so experienced with PostgreSQL).

**Comment by kjolley** [comment]
Which version of PostgreSQL are you using? 

It doesn't recognise the

`CREATE OR REPLACE language 'plpgsql';`

which is odd. This should be just initiating the language when it creates the database, the same as you did afterwards with your createlang command.

The support for 'OR REPLACE' came in with version 9.0 - are you using an older version of PostgreSQL?

**Comment by alejocrojo09** [comment]
Yes, I just checked. I am using version 8.4

**Comment by kjolley** [comment]
OK. That's the source of all your problems then. The oldest supported version of PostgreSQL is currently 9.4, so you should upgrade to a newer version. You should be able to change the line to:

CREATE language 'plpgsql';

and it will work, but I'm not sure what other features that are being used are unsupported in 8.4 (which was first released in 2009 and was end of life in 2014).
