### ISSUE TITLE
Plugins not working, bigsdb unstarted jobs stuck 0%

### ISSUE THREAD

**Issue by alejocrojo09** [kjolley/BIGSdb#603]
Hello,
I have been trying to test the plugins in BIGSdb such as SpeciesIdentification, GenomeComparator, GrapeTree, iTOL, etc. They are installed and recognized by BIGSdb. However, when I run one of the analysis plugins and set a job, it stuck in 0% for days with the remark: "unstarted jobs ahead in queue". For the offline job manager, I created the bigsdb_jobs databases in postgre and in the config.xml I enabled all plugins. I also checked in the logfiles and there is no issues or lines. The only plugin that I get results is BLAST but for the others no. Is there a special configuration step that I have to do in order to get a job done? The jobs don't run even if I have I do a simple query.

Thank you very much for your attention.

**Comment by kjolley** [comment]
You have to run bigsdb_jobs.pl as a CRON job. This retrieves a job from the queue and runs it. See https://bigsdb.readthedocs.io/en/latest/installation.html#setting-up-the-offline-job-manager.

**Comment by alejocrojo09** [comment]
Ok, because this is the configuration that I have from CRON:

[root@psbweb07 ~]# crontab -l
* * * * * bigsdb xvfb-run -a /usr/local/bin/bigsjobs >/dev/null 2>&1
05  *  *  *  *  bigsdb   /usr/local/bin/sync_user_dbase_users.pl --user_database pubmlst_bigsdb_users >/dev/null 2>&1
#Prevent prefs database getting too large
00   18 *  *  0  postgres    psql -c "DELETE FROM guid WHERE last_accessed < NOW() - INTERVAL '6 months'" bigsdb_prefs >/dev/null 2>&1
#Purge jobs older than 7 days from the jobs database.
00   5  *  *  *  postgres psql -c "DELETE FROM jobs where (stop_time IS NOT NULL AND stop_time < now()-interval '7 days') OR (status LIKE 'rejected%' AND submit_time < now()-interval '7 days')" bigsdb_jobs > /dev/null 2>&1

**Comment by kjolley** [comment]
And do you see any errors coming from CRON in your syslog?

Try running bigsjobs.pl manually as the bigsdb user to see if you get any errors (don't send the error to /dev/null for this).

**Comment by alejocrojo09** [comment]
Ok. I run manually bigsjobs.pl with bigsdb user and this is the status that I get for each plugin:
**GenomeComparator, CodonUsage, PresenceAbsence and ITOL** run succesfully, Although for GenomeComparator I get this output: 
Use of uninitialized value in length at /usr/local/lib/BIGSdb/Plugins/GenomeComparator.pm line 984.
**SpeciesIdentification** by looking at bigsdb_jobs.log I get this error:
2019/07/22 13:59:07 [ERROR] RMLSTSpecies.pm:311  - Error 500 received from rMLST REST API.
**GrapeTree** I get this output:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grapetree/grapetree.py", line 29, in <module>
    from module import app
  File "/usr/local/lib/python3.6/site-packages/grapetree/module/__init__.py", line 1, in <module>
    from flask import Flask
ImportError: No module named 'flask'
And finally from **PhyloViz** in the website there is an error sending the data to PhyloViz and I get:
Something went wrong: Missing PhyloViz connection parameters!
In bigsdb.conf I specified the username and pwd.

**Comment by kjolley** [comment]
- Genome Comparator: This is just a warning - this may well be fixed in the latest version.
- Species id: I haven't seen any connection attempt on the rMLST API today other than from a local machine not sure what's going on here.
- GrapeTree: You need to install the Python dependencies. See https://github.com/achtman-lab/GrapeTree. Make sure you're able to run this locally from the same account as you're running bigsjobs.pl from.
- PhyloViz: Are you sure you have uncommented the phyloviz_user and phyloviz_passwd fields (inactive values will have a ; in front).

**Comment by alejocrojo09** [comment]
Ok, regarding the configuration of bigsjobs, I ran it locally as you specified. What do I have to do to enable it as CRON job in order any user can run the plugins?

**Comment by kjolley** [comment]
This should run if you set up your crontab as described at https://bigsdb.readthedocs.io/en/latest/installation.html#setting-up-the-offline-job-manager (point 5). Make sure that your system allows the bigsdb user to use cron (if it isn't I would expect you to see a message in the syslog saying this).

**Comment by alejocrojo09** [comment]
Also, I realized that I did not uncomment the connection parameters for PhyloViz but now I get the following error:
Something went wrong: 500 Can't connect to online.phyloviz.net:80 (No route to host)

**Comment by kjolley** [comment]
Is your networking set up properly? online.phyloviz.net:80 is up and running.

**Comment by alejocrojo09** [comment]
Where I can  check the networking status?

**Comment by kjolley** [comment]
It varies depending on which distribution and version of Linux you're running. I can't really help with this.

Can you use a web browser on the machine running BIGSdb and navigate to e.g. online.phyloviz.net?

**Comment by alejocrojo09** [comment]
Yes, but initially I get a security warning from my web browser that the page is not trustful. I don't know if it is related with the issue that I am having from BIGSdb.

**Comment by kjolley** [comment]
It seems that the SSL certificate on the site is out of date, but the plugin doesn't use https anyway. If you specifically enter online.phyloviz.net:80 does it work ok?

**Comment by alejocrojo09** [comment]
Yes. It works when I type specifically that URL.

**Comment by kjolley** [comment]
I don't understand why then you're getting "Something went wrong: 500 Can't connect to online.phyloviz.net:80 (No route to host)". Do you have some security features that are preventing the bigsdb user from calling out?

**Comment by alejocrojo09** [comment]
Yes, I am working BIGSdb on a server. Could you please give the IP connections for PhyloViz and rMLST for SpeciesIdentification?

**Comment by kjolley** [comment]
http://online.phyloviz.net and http://rest.pubmlst.org

**Comment by alejocrojo09** [comment]
Ok. I managed to fix the cronjob for bigsjob.pl. I have another question, for iTOL I have to also allow ip connection? If so, which is the route? Thank you very much!

**Comment by alejocrojo09** [comment]
Additionally, when I was running Genome comparator using a GenBank file as a reference. I got the following output from the script and the job stuck at 0% retrieving the reference genome:

`Can't` use an undefined value as a SCALAR reference at /usr/local/lib/BIGSdb/Plugins/GenomeComparator.pm line 2230.'

Do I have to fix something from the plugin?

**Comment by kjolley** [comment]
iTOL needs to contact https://itol.embl.de

Are you entering an accession number for a Genbank file or uploading a Genbank file directly. If using an accession then it will need to be able to contact NCBI.

It would be easier to just allow the user running the jobs to make all HTTP/HTTPS connections out.

**Comment by alejocrojo09** [comment]
I am uploading the Genbank file.

**Comment by kjolley** [comment]
Are you running the latest version of Genome Comparator?

**Comment by alejocrojo09** [comment]
I am using the one from 2018.

**Comment by kjolley** [comment]
There were multiple versions in 2018 - could you let me know the version number listed in the Genome Comparator file please?

**Comment by alejocrojo09** [comment]
Ah, sorry. Version: 2.3.8

**Comment by kjolley** [comment]
I'm pretty sure I fixed this in the latest version. I recommend updating to the latest release.

**Comment by kjolley** [comment]
I think the error is due to some malformed information in the Genbank file - the newer version should give you more information about the problem and not crash. Make sure the Genbank file actually includes the genome and has some locus definitions in it.
