### ISSUE TITLE
GrapeTree Bug

### ISSUE THREAD

**Issue by alejocrojo09** [kjolley/BIGSdb#606]
Hello, I am having issues trying to work GrapeTree plugin. I have installed version 1.6. When I run from BIGSdb the plugin, from the bigsjobs.pl script I get the following output:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grapetree/grapetree.py", line 82, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/grapetree/grapetree.py", line 59, in main
    print (backend(**add_args()))
  File "/usr/local/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 709, in backend
    names, profiles, embeded = nonredundant(np.array(names), np.array(profiles))
  File "/usr/local/lib/python3.6/site-packages/grapetree/module/MSTrees.py", line 616, in nonredundant
    embeded = {names[0]:[]}
IndexError: index 0 is out of bounds for axis 0 with size 0

Am I using the correct version? I have installed all the proper modules.

**Comment by kjolley** [comment]
I'm not very familiar with troubleshooting GrapeTree. However, the latest release of GrapeTree is 1.5 - this is what I am running. Where did you get 1.6?

**Comment by alejocrojo09** [comment]
From the Github repository.

**Comment by kjolley** [comment]
Hmm, I don't know. I've just installed it from GitHub and it works ok here.
All I did was:

`git clone https://github.com/achtman-lab/GrapeTree.git`

Then copy the GrapeTree directory to /usr/local
And installed python3 dependencies using apt-get.

bigsdb.conf setting are:
```
python3_path=/usr/bin/python3
grapetree_path=/usr/local/GrapeTree
MSTree_holder_rel_path=/GrapeTree/MSTree_holder.html
```

Are you now running the latest (release) version of BIGSdb?

**Comment by alejocrojo09** [comment]
No, sorry I haven't updated.

**Comment by kjolley** [comment]
In that case I'm wondering about your dataset. The newer version of the plugin should check if your expected results can be used to create a valid tree. 

Do the results that you are trying to analyse have allelic values for the loci you are using and can you confirm that they don't all have the same profile?

**Comment by alejocrojo09** [comment]
Yes, they have. Before getting the output error and the failed flag from BIGSdb, GrapeTree check first that the input data do not have the same profile. Is more like, looking the nature of the "bug", the GrapeTree is not available to run calculations.

**Comment by alejocrojo09** [comment]
I just confirm the version. As I mentioned before, I got GrapeTree from Github which is version 1.6 but pip3.6 says that is version 2.0. I don't know if there is a version conflict.

**Comment by kjolley** [comment]
Which version of the plugin are you running?

I seem to recall there was a small change in the format of files that GrapeTree accepted. I had to make a modification to the plugin. See https://github.com/kjolley/BIGSdb/commit/c9d85ea9c8684e8ca1d39a996cc8628c1b9ceff6#diff-4872a5f283f7686a57fbc2abbe5df1cf.

Try just copying the latest Plugins/GrapeTree.pm file - it should work ok with an earlier BIGSdb.

**Comment by alejocrojo09** [comment]
Ok. Thank you very much! I decided to make the request upgrade BIGSdb for the lastest version to the server that I am working. I have a question related to the update, I check on the documentation about upgrading BIGSdb but it seem to be related with the sql script. For the software, do I have to install the lastest version from scratch or is there something easy to do in order to get the lastest scripts?

**Comment by kjolley** [comment]
You'll need to update the library files from lib/BIGSdb to /usr/local/lib/BIGSdb,
and update the css, javascript and webfonts directory (subdirectories in the root of your web site).

**Comment by alejocrojo09** [comment]
Ok. Thank you very much! I did the update however, now I get 500 Internal Server Error in the website. Is there an additional configuration step?

**Comment by kjolley** [comment]
What does the bigsdb.log and apache error log say?

You need to upgrade the databases using the upgrade SQL scripts, and the library code.

**Comment by alejocrojo09** [comment]
By looking log, it says CGI version 4.04 required--this is only version 3.51 at /usr/local/lib/BIGSdb/CGI/as_utf8.pm line 11.

**Comment by kjolley** [comment]
You are using the development branch – if you are going to install from github I would recommend you use the master branch to get the latest release. The latest release (BIGSdb 1.22.5) only needs CGI 3.47 (but you will need to update it to 4.04+ for the next release, which is likely to be this week).

**Comment by alejocrojo09** [comment]
Ok. Thank you very much! BIGSdb is now updated. However, still struggling with GrapeTree. When I launch the results to the plugin, I get a 404 Error not able to locate the dir of GrapeTree. Do I have to set directories in the root?

**Comment by kjolley** [comment]
Yes. Please see https://github.com/kjolley/BIGSdb/blob/develop/conf/bigsdb.conf#L227-L230.

**Comment by alejocrojo09** [comment]
Now everything is working correctly. Thank you very much! One last question about PhyloViz is it normal when launching the plugin, it gets stucks in "Loading Tree"?

**Comment by kjolley** [comment]
No. Although I can make it do this if all my profiles are the same. Make sure they're not.

There needs to be a check added to the code, like for GrapeTree.
