### ISSUE TITLE
Make get_refs.pl use bigsdb.conf

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#611]
Dear Keith

We are about to use get_refs.pl but the scripts and our configuration are incompatible, we don't have the same username for the db (not `postgres`), and the `refs_db` is not `bigsdb_refs`.

Could you make get_refs.pl use bigsdb.conf ?

Best regards

P.S: I also encountered this problem when working with add_user.pl

**Comment by kjolley** [comment]
This script is really old and clunky (it actually pre-dates BIGSdb as I used a version in the mlstdbNet codebase). I think it will be better for me to re-write it as a module that can be called both directly from within the web interface or from a stand-alone script. It may then be possible to call it automatically, if needed, when records are first uploaded or modified.

I'll create a separate ticket for the add_user.pl script.
