### ISSUE TITLE
error  create 'composite fields'

### ISSUE THREAD

**Issue by memoriasresiduais** [kjolley/BIGSdb#624]
Hi Keith,

We are not able to create 'composite fields' in the BIGSdb instances (in all microorganisms dbs).

Regardless the position chosen, we always get the same error message:

![image](https://user-images.githubusercontent.com/26456133/64428888-1d417d80-d0b5-11e9-901c-72734371c4ce.png)

Any thoughts on how to fix this are welcomed!

Thanks in advance,
Alexandra

**Comment by kjolley** [comment]
Sorry, not sure why this wasn't spotted earlier. I guess it's rare to set up composite fields.
