### ISSUE TITLE
Chartdirector not recognized by BIGSdb

### ISSUE THREAD

**Issue by alejocrojo09** [kjolley/BIGSdb#627]
Hello!

I have a problem with Chartdirector. I have installed it for BIGSdb in my server, however is not recognized. I have set it up in the conf file but BIGSdb still saying that is not installed. Perl installed the package in /usr/local. How do I set up so BIGSdb can enable it?

Thank you very much for your attention.

**Comment by kjolley** [comment]
It needs to be in your Perl include path. Type the following to see what this is set as:

`perl -e "print qq(@INC)"`

I have it in /etc/perl on my machine.

**Comment by alejocrojo09** [comment]
Ok, I include the path and now it works. However, in some plugins such as Gene presence, to display a heat map, the website stays longer loading (more than 30min). Is this issue related with chartdirector? How can I fix it?

**Comment by kjolley** [comment]
This is nothing to do with ChartDirector as this plugin doesn't use it. This plugin uses various Javascript libraries to display its output directly in the browser.

Are you seeing any errors in bigsdb.log or the Apache error.log?
Does your Javascript directory contain heatmap.min.js, papaparse.min.js and pivot.min.js?

What other plugins aren't displaying output?

**Comment by alejocrojo09** [comment]
I have checked bigsdb.log and no error. Also the javascript directory contains all files.

**Comment by kjolley** [comment]
Can you switch on a Javascript console and see if it's reporting an error when the page loads - In Firefox, go to menu and select Web Developer -> Web console.

**Comment by alejocrojo09** [comment]
I get that has failed loading the script of heatmap.min.js

**Comment by kjolley** [comment]
You said your javascript directory contained this file, so the browser should be able to load it.

**Comment by alejocrojo09** [comment]
The files are in the javascript directory, I don't no why the browser is not able to load it.

**Comment by alejocrojo09** [comment]
I just checked. Is not BIGSdb, is my Firefox browser. I just solved the issue.
Thank you for your help!
