### ISSUE TITLE
Autotag failing when the "Use only type alleles to identify locus" is checked

### ISSUE THREAD

**Issue by jgugliel** [kjolley/BIGSdb#653]
Hi Keith,

I encountered something weird just now. I was using a cgMLST scheme designed with the first allele of each locus tagged as "type allele". All other alleles are not type alleles.
I created a new isolate and scanned it via the web interface, with the "type allele" box ticked in the scan configuration page.

Most of the loci get an exact match (autotag).
For some loci, a CDS is detected, from a match to the type allele (allele 1). When I extract the CDS and try to add the sequence to the seqdef database, it fails because this sequence already exists and has an allele number.
If I untick the type allele box and relaunch the scan, then I get an exact match for a bunch of loci that were not tagged, including those mentioned above.

I thought type alleles were only important for new alleles definitions, but it seems that they affect autotag too.

Is this normal behavior?

Thanks

**Comment by kjolley** [comment]
Hi Julien,

It is right that selecting the type alleles option should constrain the search space, so you wouldn't expect it to find known alleles that are more divergent, but if it is finding alleles that are within the identity threshold of the type allele then it seems that it should look these up so that they are not marked as new and are identified correctly.  Seems this is a bug. 

Until I can look at this, I would recommend scanning first without type alleles but only tag known alleles, then look for new ones with the type alleles option.

**Comment by kjolley** [comment]
So far I haven't been able to replicate this. Could you let me know which other options are selected please? Is fast_scan enabled in config.xml and 'Scan selected loci together' selected?

**Comment by jgugliel** [comment]
I'll try and replicate with new isolates and keep you posted.

Le mar. 17 déc. 2019 à 10:28, Keith Jolley <notifications@github.com> a
écrit :

**Comment by jgugliel** [comment]
Ok so I just replicated it.
Here is what happened.

I scan two isolates with a cgMLST scheme with the type allele box checked. For most loci, an allele was found already present in the database.
For some loci, new alleles are found. I batch add these alleles' sequences.

I redo the scan, exact same options, I got some new results (the alleles I just added to the database).

I redo the scan, exact same options, just as a check: nothing is found.

I relaunch the scan, only change I make is I un-tick the type allele option. Exact matches (so alleles already in the database) appear.

> Could you let me know which other options are selected please?
![image](https://user-images.githubusercontent.com/1830621/71016772-f05e2700-20f5-11ea-8279-a61fc42f291c.png)

> Is fast_scan enabled in config.xml 
No. Should it be? I thought it was only to allow using exemplars?

**Comment by kjolley** [comment]
fast_scan enables searching all loci together (adds a checkbox to the above form), rather than locus-by-locus. It will use exemplars if they're available. I only ask because there are different methods called depending on these options.

Can you tell me if you get the same issue if you don't select 'Hunt for nearby start and stop codons'?

**Comment by jgugliel** [comment]
Yes same issue. To speed up things, I removed a single designation from an isolate to perform tests.
With no options selected at all, an exact match is found for the locus for which I removed the designation: allele 40 (full cds, since it's a cgMLST scheme). Stop is at position 6625, start at 7314
With only the type allele option selected, BIGSdb does not find any CDS for that locus, but a partial match with another allele. Start is again at 7314, but stop is found at position 6610. So this sequence contains the allele 40 and of course it has an internal stop codon.

**Comment by kjolley** [comment]
OK, thanks. I can replicate it now. It's happening when the allele is a different length from any of the type alleles and when selecting the hunt for nearby start/stop codons. It seems that if a nearby start/stop is found which changes the predicted start/stop sites of the match it never checks again to see if it's a known allele.

**Comment by jgugliel** [comment]
But in this case deselecting the hunt for nearby start/stop codons should
prevent this right? Because I can replicate this behaviour without the hunt.

Le mer. 18 déc. 2019 à 10:33, Keith Jolley <notifications@github.com> a
écrit :

**Comment by kjolley** [comment]
Without the hunt, it doesn't find the allele because the predicted start or stop is wrong.

**Comment by jgugliel** [comment]
Thanks a lot Keith!
