### ISSUE TITLE
conf/logging.conf duplicate line

### ISSUE THREAD

**Issue by abrozzi** [kjolley/BIGSdb#659]
Hi Keith,

I think that there is a duplicate row in the conf/logging.conf file:

log4perl.logger.BIGSdb.Job=WARN, A1

line 20 and 23. This duplication seems to produce the following error:

log4perl.logger.BIGSdb.Job redefined at /home/bigsdb/perl5/lib/perl5/Log/Log4perl/Config/PropertyConfigurator.pm line 98., referer: http://bigsdb.sci.corpnet2.com/

Bests,
-A

**Comment by kjolley** [comment]
Oops. I'll fix that, thanks.
