### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by JafarAkhondali** [kjolley/BIGSdb#671]
Hello there,
Is there any standard way to translate the UI into other languages?
By the way, I need RTL layouts :\ !

**Comment by kjolley** [comment]
Unfortunately no, there isn't. The software hasn't been written with internationalisation in mind, and support for this would require a major overhaul. Sorry.

**Comment by JafarAkhondali** [comment]
@kjolley If everything is available in your REST API, It's possible to create a whole separate UI for the system using modern frameworks like Vuejs. However, since I'm new to this project I can't judge.

If you are interested in such a thing, feel free to contact me.
