### ISSUE TITLE
tar download not working when BIGSdb is running in Plack::App::CGIBin

### ISSUE THREAD

**Issue by yghorbal** [kjolley/BIGSdb#748]
Hi Keith,

 While migrating our BIGSdb instance to CentOS 8 based server, we've been hit by a weird mod_perl issue: loading frequently the same bigsdb.pl page leads to mod_perl loosing context (`@INC` typically) and generating 500 errors.
 This [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1738385)  references random build tests failing one CentOS 8. Moreover, it also states that mod_perl upstream maintainers are no longer willing to provide fixes...
 
 Long story short, we've managed to run BIGSdb in a compatibility layer through Plack::App::CGIBin. It offres the same benefit of mod_perl (compile once, run many) and avoids the fork deluge of good old cgi-bin.

 Everything is working fine except for tar export for job files. URLs like: 
 `/cgi-bin/bigsdb/bigsdb.pl?db=blabla_isolates&page=job&id=BIGSdb_391428_1608312147_93404&output=archive`
 will generate 0 bytes tar files. 

 We tracked down the issue to [_tar_archive](https://github.com/kjolley/BIGSdb/blob/cb76026462a1be06a1635aa92d15f527d9211032/lib/BIGSdb/JobViewerPage.pm#L484)
 You've already spotted that capturing `system()` calls output was not possible in mod_perl and you did a workaroud with  backquoting call. The same is happening when running in `Plack::App::CGIBin`
 
 The fix seems to be just to always use backquoting calls regardless of running in mod_perl, plain cgi-bin or Plack::App::CGIBin. We've tested all of them and it seems to work correctly.

 It would be nice if you could just use something like this diff to make the change permanent on your side.

```diff --git a/lib/BIGSdb/JobViewerPage.pm b/lib/BIGSdb/JobViewerPage.pm
index b64e0625..314acd41 100644
--- a/lib/BIGSdb/JobViewerPage.pm
+++ b/lib/BIGSdb/JobViewerPage.pm
@@ -498,11 +498,7 @@ sub _tar_archive {
                if (@filenames) {
                        local $" = ' ';
                        my $command = "cd $self->{'config'}->{'tmp_dir'} && tar -cf - @filenames";
-                       if ( $ENV{'MOD_PERL'} ) {
-                               print `$command`;    # http://modperlbook.org/html/6-4-8-Output-from-System-Calls.html
-                       } else {
-                               system $command || $logger->error("Can't create tar: $?");
-                       }
+                       print `$command` || $logger->error("Can't create tar: $?");    # http://modperlbook.org/html/6-4-8-Output-from-System-Calls.html
                }
        }
        return;
```

Youssef

**Comment by kjolley** [comment]
Thanks Youssef. Tested and seems to work. Note that you cannot easily get an error message from a backticked call, so I check if the output is zero-length and log an error if so.
