### ISSUE TITLE
Predictable job ID

### ISSUE THREAD

**Issue by braffes** [kjolley/BIGSdb#749]
Hi Keith,

After migrating our bigsdb application with starman(PSGI) and Plack, we have noticed that the job ID was more or less predictable.
The job ID is split in 3 parts `BIGSdb_PID_Timestamp_rand(99999)` as we can see in the function get_random in `lib/BIGSdb/Utilis.pm`.

- The PID field will be the pid of a starman worker and all the workers can be found with few jobs submissions.

- The exact Timestamp can be find with the job monitor page.

- The random number is not predictable but can be bruteforce.

The complexity to find a job, with a bruteforce, become `number of starman worker * 100 000`.

It would be nice, if you can increase this complexity and be less predictable.

Thanks,

Brice.

**Comment by kjolley** [comment]
Hi Brice,

I think at some point I thought it was useful to have a timestamp in the id but this isn't really useful since job submission time is stored in the jobs database. I need to keep the format the same, so I'll use a 10 digit random number instead of the UNIX timestamp.
