### ISSUE TITLE
allele_designations not update when mering curator

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#792]
Dear Keith

After merging many accounts, we get this error 

```log
ERROR - DBD::Pg::db do failed: ERROR:  update or delete on table "users" violates foreign key constraint "ad_curator" on table "allele_designations"
DETAIL:  Key (id)=(...) is still referenced from table "allele_designations". at (...)/maintenance/sync_user_dbase_users.pl line 640.
```

After investigation, this account was a curator account which will/is merged with an other curator account, and as the log says, indeed in allele_designations it is still the old id.

I have a workaround for out migration, but it might be useful to prevent such bug in futur version.

Best regards

**Comment by bryan-brancotte** [comment]
P.S: same for `allele_sequences`

**Comment by kjolley** [comment]
Thanks Bryan - I've identified the cause and have a fix.
