### ISSUE TITLE
Prevent case ambiguity in user_name when registering

### ISSUE THREAD

**Issue by bryan-brancotte** [kjolley/BIGSdb#795]
Dear Keith, 

While migrating to site wide users settings, we encountered multiple case of two accounts, one for `Bob` and the other for `bob` while not being the same person (different email, names, affiliation).

I searched in the [code](https://github.com/kjolley/BIGSdb/blob/034904151778704c8a7f7d4cb90da9685f79ca8b/lib/BIGSdb/UserPage.pm#L509-L537) if we were preventing futur creation of account with the same user_name in a different case, and I think we don't.

Could you implement such mechanism ? It would prevent mistake, or even malicious account creation counting on user/curator misreading a username.

Best regards

**Comment by kjolley** [comment]
Sorry this took so long!
