### ISSUE TITLE
File does not exist css font jquery

### ISSUE THREAD

**Issue by abrozzi** [kjolley/BIGSdb#817]
Hi Keith,

got this in my ```/var/log/httpd/error_log```

```
File does not exist: /var/www/html/css/jquery-ui.css, referer: http://bigsdb.sci.corpnet2.com/
[Wed Jan 12 11:12:01 2022] [error] [client 11.156.26.199] File does not exist: /var/www/html/css/font-awesome.css, referer: http://bigsdb.com/
[Wed Jan 12 13:29:04 2022] [error] [client 11.156.26.199] File does not exist: /var/www/html/css/jquery-ui.css, referer: http://bigsdb.com/index_5942rftXsdBn1.html
[Wed Jan 12 13:29:04 2022] [error] [client 11.156.26.199] File does not exist: /var/www/html/css/font-awesome.css, referer: http://bigsdb.com/index_5942rftXsdBn1.html
```
Any hints where to download them and place in the right dir?

Bests,
-A

**Comment by kjolley** [comment]
I don't think this is coming from your installation. This looks like an external client attempting to access these files on your web server, which don't exist.

These filenames haven't been used in recent versions of BIGSdb. The current versions are:

fontawesome-all.css
jquery-ui.min.css

Presumably you're not seeing these errors when using BIGSdb yourself?
