### ISSUE TITLE
conf directory to /etc/bigsdb/

### ISSUE THREAD

**Issue by abrozzi** [kjolley/BIGSdb#820]
Dear Keith,

I have a question on installation.
Following your instructions:

```
Copy the contents of the conf directory to /etc/bigsdb/. 
```

but if I copy instead in ``` /etc/bigsdb/defeault ``` in which file shall I change the pointer accordingly?

Hope I explain myself,
-A

**Comment by kjolley** [comment]
This is hard-coded in lots of files. There is no support for changing this location.

You would need to update the value of CONFIG_DIR and DBASE_CONFIG_DIR in every script that it is defined. This is every .pl script found in the top-level directory (bigsdb.pl, bigscurate.pl, bigsjobs.pl, bigsrest.pl), and every script in the scripts set of sub-directories.

**Comment by abrozzi** [comment]
Ok! Thank you Keith.

I asked because this way:

```
# /etc/bigsdb
default -> v-1.24
v-1.24
```

during upgrades to newer versions, one could modify all the conf files inside the new dir and change only 1 symbolic link.

HTH
-A

**Comment by abrozzi** [comment]
Ok! Thank you Keith.

I asked because this way:

```
# /etc/bigsdb
default -> v-1.24
v-1.24
```

during upgrades to newer versions, one could modify all the conf files inside the new dir and change only 1 symbolic link.

HTH
-A

**Comment by kjolley** [comment]
Most of the conf files shouldn't change much between versions and most will be customised to your site. You could always symlink individual conf files, e.g. bigsdb.conf -> v-1.24.
