### ISSUE TITLE
Emboss issue with unavailable file 

### ISSUE THREAD

**Issue by braffes** [kjolley/BIGSdb#845]
Hi Keith,

We found an issue when we used the translation functionality in LocusExplorer.pm file.

Because we do some jobs on our cluster, the **secure_tmp_dir** and **tmp_dir** is not located at the same place. Only **secure_tmp_dir** is accessible on our cluster.

So the EMBOSS job will fail because the file is not accessible on our cluster. Is it possible to change the value for both variable https://github.com/kjolley/BIGSdb/blob/4881536d4e45b4788f4b2c8d8b5f21bae5b1a1af/lib/BIGSdb/Plugins/LocusExplorer.pm#L759-L760
by
```
my $out_file   = "$self->{'config'}->{'secure_tmp_dir'}/$temp.pep";
my $final_file = "$self->{'config'}->{'secure_tmp_dir'}/$temp.aln";
```

I don't know how to test it, but the change will maybe break the following function because the file will not be accessible for the user job? 
https://github.com/kjolley/BIGSdb/blob/4881536d4e45b4788f4b2c8d8b5f21bae5b1a1af/lib/BIGSdb/Plugins/LocusExplorer.pm#L190-L195

Feel free to ask more information if needed.

Thanks for your comprehension,

Brice

**Comment by braffes** [comment]
Hi Keith, 

To take GenomeComparator.pm as en example, all the functionnality seems to run locally.

I grep `system` to see what is executed and to find what can be used on our cluster. 
For Blast, all the input/ouput seems to use `secure_tmp_dir`
For Blast, all the input/ouput seems to use `secure_tmp_dir`
For Blast, all the input/ouput seems to use `secure_tmp_dir`

**Comment by kjolley** [comment]
Yes. I cannot change this. When a plugin creates an output file that is made available to the user then it has to be accessible to the browser.
