### ISSUE TITLE
Plugin jobs run by admins in the curator interface may not see all available isolate records

### ISSUE THREAD

**Issue by kjolley** [kjolley/BIGSdb#849]
Admins in the curator interface can query the database and see all private records belonging to other users, whereas in the standard user interface they will only see public records, their own private records, and private records shared with them. Offline jobs only see records accessible to the logged in user as if they were in the standard user interface, so jobs run by admins in the curator interface will not see private records that are accessible to them in that interface. This is confusing and the same dataset should be available for querying and offline analysis if run from the curator interface.

**Comment by sbridel** [comment]
It would be awesome to keep a track of private records in the exported table. Today, it is just shown on the interface, but the information is not present when exported.

**Comment by kjolley** [comment]
OK. I've added that as a separate ticket: https://github.com/kjolley/BIGSdb/issues/850.
