### ISSUE TITLE
jobs remain in queue and are not sent to run

### ISSUE THREAD

**Issue by abrozzi** [kjolley/BIGSdb#885]
Dear Keith,

we completed the installation of bigsdb and testing Genome Comparator we saw that jobs remain in queue and they never progress to running.
We searched for the the error but we struggle to find it.

Do you have any hint or suggestion about which files should we check to find it out?

- Lat error in var/httpd/error_log was a missing Bioperl.pm module that we installed.
- A /tmp directory wasn't writable from apache and we changed its permissions

Thank you very much for any help you can provide us,
-A

**Comment by kjolley** [comment]
You need to run bigsjobs.pl from CRON.

https://bigsdb.readthedocs.io/en/latest/installation.html#setting-up-the-offline-job-manager

**Comment by abrozzi** [comment]
Hi Keith,

solved by adding in crontab file the perl environment variable:

PERL5LIB="/root/perl5/lib/perl5:/usr/local/lib64/perl5"

HTH
-A
