### ISSUE TITLE
template.pm Module Perl Template dependency

### ISSUE THREAD

**Issue by abrozzi** [kjolley/BIGSdb#950]
Hi Keith,
during the upgrade to the latest version I had to install the Perl Module Template.

https://metacpan.org/release/ABW/Template-Toolkit-2.00-beta4/view/lib/Template.pm

Can you confirm is it a Perl dependency for Bigsdb?

Same for PDL:

https://metacpan.org/pod/PDL

Bests,
Alex

**Comment by kjolley** [comment]
HI Alex,

Yes, Template is needed. The requirement was added with version 1.31.0 as it's used to format arbitrary analysis data within an isolate information page (https://github.com/kjolley/BIGSdb/releases/tag/v_1.31.0). It is also used for a new Reports plugin. I will add this to the dependencies page on the documentation. 

PDL is only used by the lincodes.pl script. You only need this if you are assigning LINcodes to a cgMLST scheme (https://pubmed.ncbi.nlm.nih.gov/35700230/).

**Comment by kjolley** [comment]
Note dependencies listed at https://bigsdb.readthedocs.io/en/latest/dependencies.html.
