### ISSUE TITLE
Suggestion on round and lround module of POSIX 

### ISSUE THREAD

**Issue by abrozzi** [kjolley/BIGSdb#995]
Dear Keith,

I noticed that `POSIX `module triggers some conflicts with perl versioning (5.16 versus newer).
Since `lround `is only used once in `/lib/BIGSdb/Plugins/SeqbinBreakdown.pm` I would humbly suggest to replace it with something simple but effective like:

```
sub round {
    my ($number) = @_;
    return int($number + 0.5 * ($number <=> 0));
}
```

HTH
-A

**Comment by kjolley** [comment]
Hi Alessandro,

This seems sensible and a good solution. Thanks.
